name: wireworks
favicon: null
layout_spectrum: 0.50196
typography_spectrum: 0.16949
title: Wireworks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#231f03'
    - '#7e6f0b'
    - '#463e06'
    - '#cab212'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
