name: wireworks
favicon: null
layout_spectrum: 0.50196
typography_spectrum: 0.16949
title: Wireworks
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f0f0f'
    - '#1b1b1b'
    - '#272727'
    - '#343434'
    - '#404040'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
